parameters:
#    golden_bird_labs_replace_assets.example.class: GoldenBirdLabs\ReplaceAssetsBundle\Example

services:
#    golden_bird_labs_replace_assets.example:
#        class: %golden_bird_labs_replace_assets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
